### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by thecoconutstudio** [ladderio/ngx-tribute#1]
I downloaded the source, ran `npm install` then `ng serve`

It returned `ERROR in src/app/app.module.ts(5,32): error TS2307: Cannot find module 'ngx-tribute'.`

I then ran `npm i tributejs ngx-tribute`

now it returns 
`ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '/ngx-tribute-master/dist/ngx-tribute' in '/ngx-tribute-master/src/app'`

**Comment by agarbund** [comment]
Indeed, the docs where not fully correct. You need to run `npm run build-lib` before `ng serve`. I updated the docs. I'd recommend you to download a fresh repo ( as you made some changes in `package.json` by running `npm i tributejs ngx-tribute` ) and check if everything works now.

**Comment by thecoconutstudio** [comment]
I'm still struggling getting this to run. When importing into an existing project. I've run `npm i tributejs ngx-tribute` added `NgxTributeModule` to imports but when running `ionic serve` I get 

`Uncaught Error: Template parse errors:
Can't bind to 'ngxTribute' since it isn't a known property of 'input`

**Comment by agarbund** [comment]
Can I see a reproduction of this issue somewhere?

**Comment by thecoconutstudio** [comment]
I started a new project and it compiled fine with no errors. It must be something to do with my current project. I'll close this for now.
