### ISSUE TITLE
block has wrong position 

### ISSUE THREAD

**Issue by denys-aponiuk** [ladderio/ngx-tribute#10]
I have problem related to position of block. When I write @ and there is place below, everything ok, but if there isn't, block jumps in different places
![Снимок экрана 2019-04-24 в 11 29 39](https://user-images.githubusercontent.com/34792481/56644820-24776a00-6685-11e9-81e5-5e4c64cdac41.png)
![Снимок экрана 2019-04-24 в 11 29 10](https://user-images.githubusercontent.com/34792481/56644838-2c370e80-6685-11e9-9da6-3c98240e55a7.png)

**Comment by agarbund** [comment]
This rather seems like an issue with Tribute itself, not it's Angular wrapper. Check the issues regarding positioning https://github.com/zurb/tribute/issues?utf8=%E2%9C%93&q=position

**Comment by denys-aponiuk** [comment]
thanks a lot
