### ISSUE TITLE
Document onMentioned emitter 

### ISSUE THREAD

**Issue by bdavies** [ladderio/ngx-tribute#12]
Hello!

Thanks for putting together this wrapper for TributeJS. I've been using it recently, and today realised that it would be **really** useful if I could subscribe to an EventEmitter which emits when a mention is added.

...It turns out that this already exists, but isn't in the documentation. I only happened to noticeit whilst looking at the library source. I tested it locally (v1.1), and it seems to do exactly what I need! 🎉 

`(onMentioned)="yourMethod($event)"`

If I get time, I'll raise a small PR to add this to the documentation.

Thanks again 🙌

**Comment by agarbund** [comment]
Thanks for pointing that out. Docs updated :)
