### ISSUE TITLE
Touch event causing input to lose focus

### ISSUE THREAD

**Issue by tmk1991** [ladderio/ngx-tribute#14]
**How can we reproduce this bug?**

1. Attach TributeJS to a contenteditable div
2. Chrome debug view with mobile iOS format selected (be sure to refresh after setting up the debug console/tools.
3. use tribute @_ _ _ and when clicking/tapping/touching on a menu item, the input loses focus.

**What did you expect to happen?**
The focus and cursor should stay at the end. When in chrome without the debug tools open, it behaves as expected.

**What happened instead?**
Cursor loses focus

I did look into the source code and notice that the click function is executing with a preventDefault(). I'm wondering if there needs to be a touchstart/touchend event(s)? 

        key: 'click',
        value: function click(instance, event) {
            var tribute = instance.tribute;
            if (tribute.menu && tribute.menu.contains(event.target)) {
                var li = event.target;
                event.preventDefault();
                event.stopPropagation();
                while (li.nodeName.toLowerCase() !== 'li') {
                    li = li.parentNode;
                    if (!li || li === tribute.menu) {
                        throw new Error('cannot find the <li> container for the click');
                    }
                }
                tribute.selectItemAtIndex(li.getAttribute('data-index'), event);
                tribute.hideMenu();

                // TODO: should fire with externalTrigger and target is outside of menu
            } else if (tribute.current.element && !tribute.current.externalTrigger) {
                tribute.current.externalTrigger = false;
                setTimeout(function () {
                    return tribute.hideMenu();
                });
            }
        }

**Comment by agarbund** [comment]
Thanks for reporting. This repo is just an Angular wrapper and this bug seems like an issue with Tribute.js itself, please report it in [original Tribute.js repo](https://github.com/zurb/tribute).
