### ISSUE TITLE
Feature Request - being able to control when the list modal opens and closes

### ISSUE THREAD

**Issue by ConnorWin** [ladderio/ngx-tribute#18]
It would be useful to programmaticly trigger when tribute opens and closes using this library. Like hitting "tab" on a list option would cause an @mention but then tribute remains open and then hitting "enter" would cause and @mention and tribute would close.

**Comment by agarbund** [comment]
Thanks for the suggestion. This is rather sth to ask for in [the native library](https://github.com/zurb/tribute) thou, not in Angular wrapper.
