### ISSUE TITLE
I followed all the steps as mentioned but It's not working.

### ISSUE THREAD

**Issue by karthikdeva** [ladderio/ngx-tribute#29]
Even these examples also not working.
https://ladderio.github.io/ngx-tribute/
 I'm trying to do with contenteditable options in latest angular version. Pls let me know if there any solution for this.

**Comment by agarbund** [comment]
Just checked the demo page and it works as it should. The menu is triggered by putting "@" character. Can you share a Stackblitz with code that is not working for you?

**Comment by karthikdeva** [comment]
It's working :) thanks and autocomplete mode made my job very easy... thanks guys for the quick reply :)
