### ISSUE TITLE
How can I extend the Directive

### ISSUE THREAD

**Issue by thecoconutstudio** [ladderio/ngx-tribute#3]
I would like to extend your NgxTribute directive so I can create a wrapper for additional functionality.

I've originally have tried something like this - 
```
import {NgxTributeDirective} from "ngx-tribute/lib/ngx-tribute.directive";
@Directive({
  selector: '[tagging]' // Attribute selector
})
export class TaggingDirective extends NgxTributeDirective<any> {

  constructor(element: ElementRef, formControlName: FormControlName, formControlDirective: FormControlDirective, ngModelDirective: NgModel) {
    super(element, formControlName, formControlDirective, ngModelDirective)

    this.options = {
      values: [{value: 'Phil Heartman', firstName: 'pheartman'},
        {value: 'Gordon Ramsey', firstName: 'gramsey'}],
      selectTemplate: function (item) {
        return '<span class="replace_text" id="'+item.original.id +'"><a href="http://zurb.com" target="_blank" title="'  +item.original.value  +'">'  +item.original.value  +'</a></span>';
      },
    };
  }
}
```

But I get the following error - `Uncaught Error: Cannot find module "ngx-tribute/lib/ngx-tribute.directive"
`

**Comment by agarbund** [comment]
Please update to the latest version, the directive class was not exposed from the NPM module.

After updating you should be able to do:
```
import {NgxTributeDirective} from "ngx-tribute";
```

Remember to add `@Optional()` decorators to params of `constructor`. Check https://github.com/ladderio/ngx-tribute/blob/master/projects/ngx-tribute/src/lib/ngx-tribute.directive.ts#L22

**Comment by thecoconutstudio** [comment]
Awesome thanks 👍
