### ISSUE TITLE
Bug when deleting Mention on Android

### ISSUE THREAD

**Issue by thecoconutstudio** [ladderio/ngx-tribute#5]
There is a bug when deleting a mention on Android only.

For example, say my div container has the following content

`<div tagging="options" contenteditable="true" data-tribute="true">Hello <span contenteditable="false" class="replace_text" id="479"><a href="http://zurb.com" target="_blank">Jon Doe</a></span></div>`

Pressing backspace/delete duplicates the last word in the Mention `Doe`

`<div tagging="options" contenteditable="true" data-tribute="true">Hello <span contenteditable="false" class="replace_text" id="479"><a href="http://zurb.com" target="_blank">Jon Doe</a></span>Doe</div>`

This will happen even when there is plain text after the Mention/span. For example

`<div tagging="options" contenteditable="true" data-tribute="true">Hello <span contenteditable="false" class="replace_text" id="479"><a href="http://zurb.com" target="_blank">Jon Doe</a></span> you are great.</div>`

`you are great` gets deleted as expected but then when the cursor gets to the `e` of `Doe` it starts duplicating again.

This also happens when the Mention is just one word as well.

Android version 7.1.2

**Comment by agarbund** [comment]
I doubt it's related to `ngx-tribute`, or even `tributejs` as they're only responsible for inserting text from mention. Could you put this text directly in component, without using `ngx-tribute`, and confirm, that this bug occurs only if using `tributejs` and not otherwise?

**Comment by thecoconutstudio** [comment]
yes this only happens when using ngx-tribute, and only on Android. iOS and desktop are fine.

**Comment by thecoconutstudio** [comment]
Found someone else reporting the same issue - https://github.com/zurb/tribute/issues/166

**Comment by agarbund** [comment]
Closing as it's related to Zurb itself, and not the Angular wrapper.
