### ISSUE TITLE
Is there a way to expose the `isActive` or `showMenuForCollection`

### ISSUE THREAD

**Issue by rcavezza** [ladderio/ngx-tribute#7]
I'm trying to customize my implementation of tribute. I'm using this library, and I'm not sure if there's a way to use this library with `tribute.isActive` and `tribute.showMenuForCollection`

I didn't see anything in the docs that would suggest an easy way to do this. Can you let me know if it's possible with `ngx-tribute` or if I have to customize the original `tributejs`.

I'm using 

```
  options: any = {
    collection: [
      {
        trigger: '@',
      .....
``` 
and 

```<div class="human-readable-edit" contenteditable="true"
[ngxTribute]="options"
...
>
```

Any insights would be appreciated.

**Comment by agarbund** [comment]
I've published version `1.1.0` which allows to do this. Check the updated [demo page](https://ladderio.github.io/ngx-tribute/) and [demo code](https://github.com/ladderio/ngx-tribute/blob/master/src/app/app.component.ts#L42) for the working example.
