### ISSUE TITLE
Any tips for getting ngx-tribute to run locally

### ISSUE THREAD

**Issue by rcavezza** [ladderio/ngx-tribute#8]
I'm testing this locally pulling down an experimental version of `tributejs` I've been working on. I can't get this to run locally without referring to the npm version. Any tips or insights @agarbund ?

**Comment by rcavezza** [comment]
For more context, I forked the repo to `rcavezza/ngx-tribute` and I'm currently getting `ERROR in src/app/components/app.module.ts(24,34): error TS2307: Cannot find module '../../../node_modules/ngx-tribute'.`

If you change a project's package.json file to refer to the library as `"ngx-tribute": "https://github.com/ladderio/ngx-tribute.git",` instead of `ngx-tribute: "^1.1.0"`, and try to start an angular project, you'll see a message like the following: 

```ERROR in src/app/components/app.module.ts(24,34): error TS2307: Cannot find module 'ngx-tribute'.
src/app/components/main/path/to/component/regular.component.ts(11,37): error TS2307: Cannot find module '../../../../../../../../../node_modules/ngx-tribute'.

 ｢wdm｣: Failed to compile.```

**Comment by rcavezza** [comment]
Figured it out! I think I'm going to remove `/dist` from the `.gitignore` file in my work and link directly to the `dist/` folder.

**Comment by agarbund** [comment]
@rcavezza did you follow all steps listed in [Contributing section](https://github.com/ladderio/ngx-tribute#contributing)?

**Comment by rcavezza** [comment]
Thanks! I missed that on the first go-around.
